CREATE TABLE IF NOT EXISTS events(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    place character varying(255) NOT NULL,
    start_time timestamptz NOT NULL
);
ALTER TABLE events ADD COLUMN created_at TIMESTAMPTZ;
ALTER TABLE events ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE events ADD COLUMN updated_at TIMESTAMPTZ;
ALTER TABLE events ALTER COLUMN updated_at SET DEFAULT now();

CREATE TABLE IF NOT EXISTS users
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    rol character varying(20) NOT NULL,
    can_login boolean NOT NULL,
    password character varying(255),
    phone character varying(20),
    active boolean NOT NULL,
    UNIQUE (email)
);
ALTER TABLE users OWNER to postgres;
ALTER TABLE users ADD COLUMN created_at TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE users ADD COLUMN updated_at TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT now();
